[package]
name = "image_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "imagecli"
path = "src/imagecli.rs"


[dependencies]
image = "0.23.7"
structopt = "0.3.15"
